version: 0.2

phases:
  install:
    commands:
      - aws --version && git --version && pip --version && python --version
      - pip install --upgrade awscli
      - apt-get update
  build:
    commands:
      - echo Build started on `date`
      - echo ${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - sh foundation/fetch-parameters.sh
      - aws cloudformation package --template-file foundation/serverless.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file NewSamTemplate.yaml
      - dotnet restore
      - dotnet build
      - dotnet publish
      - cd o365-audit/bin/Debug/netcoreapp1.1/publish/
      - zip ../../../../publish.zip *
      - aws s3 cp ../../../../publish.zip s3://vms-audit-o365-${ACCOUNT_NAME}/${CODEBUILD_RESOLVED_SOURCE_VERSION}/publish.zip
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
    - publish.zip
    - parameters.json
  discard-paths: yes